language: node_js
node_js:
      - "stable"

      cache:
        dependencies:
          node-modules

scripts:
    - yarn install
    - yarn test
    - yarn build

deploy:
  provider: surge
  skip_cleanup: true
  domain: demonic-dock.surge.sh
  project: ./build/

on:
  branch: master